services:
  # Frontend (Nginx serving host-build)
  frontend:
    build:
      context: .
      dockerfile: apps/web-client/Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
    restart: always

  # Backend (Node.js running host-build dist)
  backend:
    build:
      context: .
      dockerfile: apps/web-server/Dockerfile
    ports:
      - 3001:3001
    env_file:
      - ./apps/web-server/.env
    restart: always

  # Discord Bot
  discord-bot:
    build:
      context: .
      dockerfile: apps/discord-bot/Dockerfile
    ports:
      - 3002:3002
    env_file:
      - ./apps/web-server/.env
    depends_on:
      - backend
    restart: always

