export const ROLES = {
    USER: 'user',
    DONOR: 'donor',
    HELPER: 'helper',
    MODERATOR: 'moderator',
    STAFF: 'staff',
    ADMIN: 'admin',
    FOUNDER: 'founder',
    DEVELOPER: 'developer',
    KILLU: 'killu',
    NEROFERNO: 'neroferno'
} as const;

export type Role = typeof ROLES[keyof typeof ROLES];

export const STAFF_ROLES: Role[] = [
    ROLES.HELPER,
    ROLES.MODERATOR,
    ROLES.STAFF,
    ROLES.ADMIN,
    ROLES.FOUNDER,
    ROLES.DEVELOPER,
    ROLES.KILLU,
    ROLES.NEROFERNO
];

const ROLE_LEVELS: Record<Role, number> = {
    [ROLES.USER]: 0,
    [ROLES.DONOR]: 0,
    [ROLES.HELPER]: 1,
    [ROLES.MODERATOR]: 2,
    [ROLES.STAFF]: 2,
    [ROLES.ADMIN]: 3,
    [ROLES.FOUNDER]: 4,
    [ROLES.DEVELOPER]: 4,
    [ROLES.KILLU]: 5,
    [ROLES.NEROFERNO]: 6
};

export const getRoleLevel = (role: string): number => {
    return ROLE_LEVELS[role.toLowerCase() as Role] ?? -1;
};

export const isStaffRole = (role: string): boolean => {
    return STAFF_ROLES.includes(role as Role);
};

export const PERMISSIONS = {
    VIEW_DASHBOARD: [ROLES.MODERATOR, ROLES.ADMIN, ROLES.DEVELOPER, ROLES.KILLU, ROLES.NEROFERNO],
    VIEW_USERS: [ROLES.MODERATOR, ROLES.ADMIN, ROLES.DEVELOPER, ROLES.KILLU, ROLES.NEROFERNO],
    EDIT_USER_ROLE: [ROLES.ADMIN, ROLES.KILLU, ROLES.NEROFERNO],
    EDIT_USER_METADATA: [ROLES.ADMIN, ROLES.DEVELOPER, ROLES.KILLU, ROLES.NEROFERNO],
    MANAGE_NEWS: [ROLES.MODERATOR, ROLES.ADMIN, ROLES.DEVELOPER, ROLES.KILLU, ROLES.NEROFERNO],
    MANAGE_WIKI: [ROLES.MODERATOR, ROLES.ADMIN, ROLES.DEVELOPER, ROLES.KILLU, ROLES.NEROFERNO],
    MANAGE_EVENTS: [ROLES.MODERATOR, ROLES.ADMIN, ROLES.DEVELOPER, ROLES.KILLU, ROLES.NEROFERNO],
    MANAGE_GAMIFICATION: [ROLES.DEVELOPER, ROLES.KILLU, ROLES.NEROFERNO],
    MANAGE_TICKETS: [ROLES.MODERATOR, ROLES.ADMIN, ROLES.DEVELOPER, ROLES.KILLU, ROLES.NEROFERNO],
    MANAGE_SUGGESTIONS: [ROLES.MODERATOR, ROLES.ADMIN, ROLES.DEVELOPER, ROLES.KILLU, ROLES.NEROFERNO],
    MANAGE_POLLS: [ROLES.MODERATOR, ROLES.ADMIN, ROLES.DEVELOPER, ROLES.KILLU, ROLES.NEROFERNO],
    MANAGE_DONATIONS: [ROLES.ADMIN, ROLES.KILLU, ROLES.NEROFERNO],
    VIEW_DONORS: [ROLES.ADMIN, ROLES.DEVELOPER, ROLES.KILLU, ROLES.NEROFERNO],
    MANAGE_STAFF_CARDS: [ROLES.ADMIN, ROLES.DEVELOPER, ROLES.KILLU, ROLES.NEROFERNO],
    MANAGE_STAFF_TASKS: [ROLES.MODERATOR, ROLES.ADMIN, ROLES.DEVELOPER, ROLES.KILLU, ROLES.NEROFERNO],
    MANAGE_SITE_CONFIG: [ROLES.ADMIN, ROLES.DEVELOPER, ROLES.KILLU, ROLES.NEROFERNO],
    MANAGE_MAINTENANCE: [ROLES.ADMIN, ROLES.KILLU, ROLES.NEROFERNO],
    VIEW_AUDIT_LOG: [ROLES.ADMIN, ROLES.KILLU, ROLES.NEROFERNO],
    VIEW_SYSTEM_LOGS: [ROLES.DEVELOPER, ROLES.KILLU, ROLES.NEROFERNO],
    VIEW_CONSOLE: [ROLES.NEROFERNO, ROLES.KILLU, ROLES.DEVELOPER, ROLES.ADMIN],
} as const;

export type Permission = keyof typeof PERMISSIONS;
